# Generated by Django 5.1.3 on 2024-12-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("email", "role"),
                "verbose_name": "Пользователя",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
