# Generated by Django 5.1.3 on 2024-11-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("email", "role"),
                "verbose_name": "Пользователя",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
