# Generated by Django 5.1.3 on 2024-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_email_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="uid"
            ),
        ),
    ]
