# Generated by Django 5.1.3 on 2024-12-03 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время отзыва"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(max_length=400, verbose_name="Текст отзыва"),
        ),
    ]
