# Generated by Django 5.1.3 on 2024-11-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
