# Generated by Django 5.1.3 on 2024-12-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_ad_is_active_ad_updated_at_alter_ad_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активность"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата и время изменения объявления"
            ),
        ),
    ]
