# Generated by Django 5.1.3 on 2024-12-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_alter_ad_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания объявления"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Признак активности"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата изменения объявления"
            ),
        ),
    ]
