# Generated by Django 5.1.3 on 2024-12-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0006_alter_ad_created_at_alter_ad_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
    ]
