# Generated by Django 5.1.3 on 2024-12-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0008_remove_ad_is_active_remove_ad_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(
                default="Автор пока не создал описания", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Стоимость товара/услуги"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название объявления"),
        ),
    ]
