# Generated by Django 5.1.3 on 2024-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0011_alter_ad_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата создания объявления"
            ),
        ),
    ]
